// <auto-generated />
namespace QuestionnaireMonthly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class fixmodelanswer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixmodelanswer));
        
        string IMigrationMetadata.Id
        {
            get { return "201602111828530_fix-model-answer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
