// <auto-generated />
namespace QuestionnaireMonthly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class fixclassanswer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixclassanswer));
        
        string IMigrationMetadata.Id
        {
            get { return "201602101901399_fix-class-answer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
