// <auto-generated />
namespace QuestionnaireMonthly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class updatetypetofieldorderinquestion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetypetofieldorderinquestion));
        
        string IMigrationMetadata.Id
        {
            get { return "201602051642103_update-type-to-field-order-in-question"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
